<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 https://maven.apache.org/xsd/maven-4.1.0.xsd"
         root="true">

    <modelVersion>4.1.0</modelVersion>

    <parent>
        <groupId>ca.mikegabelmann.maven</groupId>
        <artifactId>parent</artifactId>
        <version>1.1-SNAPSHOT</version>
    </parent>

    <groupId>mikegabelmann</groupId>
    <artifactId>photo</artifactId>
    <version>0.9-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>backup</name>
    <description>
        Backup files if they don't exist in the destination directory or newer. Also provides some other utilities
        for performing backups.
    </description>

    <scm>
        <connection>scm:git:https://github.com/mgabelmann/backup.git</connection>
        <developerConnection>scm:git:https://github.com/mgabelmann/backup.git</developerConnection>
        <url>https://github.com/mgabelmann/backup</url>
    </scm>

    <properties>
        <itext.version>8.0.4</itext.version>
    </properties>

    <dependencies>
        <!-- logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.17</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <version>2.24.3</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.19.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-imaging</artifactId>
            <version>1.0.0-alpha5</version>
            <scope>compile</scope>
        </dependency>

        <!-- NOTE: use for all functionality -->
        <!--<dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>itext-core</artifactId>
            <version>${itext.version}</version>
            <type>pom</type>
            <scope>compile</scope>
        </dependency>-->

        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>kernel</artifactId>
            <version>${itext.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>io</artifactId>
            <version>${itext.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.itextpdf</groupId>
            <artifactId>layout</artifactId>
            <version>${itext.version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.jgoodies/jgoodies-forms -->
        <dependency>
            <groupId>com.jgoodies</groupId>
            <artifactId>jgoodies-forms</artifactId>
            <version>1.9.0</version>
        </dependency>


        <!-- TESTING -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

        </plugins>
    </build>

</project>
